
set(FIND_NCURSESW_PATHS C:/msys64/mingw64)

find_path(NCURSESW_INCLUDE_DIR curses.h PATH_SUFFIXES include/ncursesw PATHS ${FIND_NCURSESW_PATHS})
find_library(NCURSESW_LIBRARY NAMES ncursesw PATH_SUFFIXES lib PATHS ${FIND_NCURSESW_PATHS})